### ISSUE TITLE
Configuration Error when debugging ASP service

### ISSUE THREAD

**Issue by jo-me** [aspnet/MicrosoftConfigurationBuilders#32] opened 2018-07-12 08:37 UTC
Hi,
with preview2 and 1.0.2 I keep getting the following error message when starting the service in debug mode.

![image](https://user-images.githubusercontent.com/10351272/42621895-4d9c2f08-85bf-11e8-9432-8da4a42b78cc.png)

It is not happy with the configbuilders attribute in the appsettings part of the web.config.

What is the issue here?

**Comment by StephenMolloy** [comment] 2018-07-12 16:34
Usually this means there is a mistake in how you have configured the AzureKeyVault config builder. If you can attach a debugger, you could get a better idea of what the issue is. Of if you want to send me your config file, I could see if anything looks obviously incorrect.

Unfortunately when we added the config builders feature to the framework, the error reporting story was somewhat incomplete. And it seems to be most relevant to the AzureKeyVault config builder, as that seems to be the one that is easiest to get wrong. The next release of the framework addresses this and you'll see a more informative YSOD, but that release is not right around the corner. Attach a debugger to see the actual error. Or build a simple console app that prints appSettings and use the config builder there where you will get to see the entire exception stack.

**Comment by jo-me** [comment] 2018-07-13 13:21
Ok, I will try this approach with the console app.
The thing is, it worked for me previously (at least for some settings) and then stopped working. 

For other colleagues, it also worked when they first set it up, but eventually broke. Most recently after the Visual studio update to 15.7.5.

**Comment by StephenMolloy** [comment] 2018-07-13 18:19
It could absolutely be some issue other than misconfiguration. All issues big and small get wrapped up in the same unhelpful YSOD. Like I said, we've addressed that in the future framework. But it is what it is with the current release.

Please let me know if you solve this, or if you need more help when you see the more detailed error. If there is an issue with the key vault config builder, I'd obviously love to know. ;)

**Comment by martinoss** [comment] 2018-10-18 15:43
I'm also struggling with unhelpful YSODS. Glad to hear that it is addressed. 
Will it be part of .NET Framework 4.8 or earlier?

**Comment by imteam** [comment] 2018-10-18 15:47
I have the same problem. I'm using vs2017 15.8.7 and .Net framework 4.7.1.
I'm also interested to know in which version it will be solved.

**Comment by StephenMolloy** [comment] 2018-12-04 22:45
This was barely on the radar for 4.7.2, so it didn't get addressed back then. It has been checked in to vNext (4.8) for some time now. The latest early access builds should have it if you want to take a peek.

**Closed by StephenMolloy** 2018-12-04 22:45 UTC
